package vistas;

import conexiones.Server;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FrmMainPanel extends javax.swing.JFrame {

    FrmMenu objMenu;
    FrmCrearPartida objCrearPartida;

    public FrmMainPanel() {
        initComponents();
        this.setTitle("Patolli");
        this.setLocationRelativeTo(null);
        agregarFrmMenu();
    }

    public void agregarFrmMenu() {
        try {
            objMenu = new FrmMenu(this);
            objMenu.setMaximum(true);
            objMenu.setVisible(true);
            jdesk.add(objMenu);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void agregarFrmCrearPartida() {
        try {
            objCrearPartida = new FrmCrearPartida(this);
            objCrearPartida.setMaximum(true);
            objCrearPartida.setVisible(true);
            jdesk.add(objCrearPartida);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void crearServer() {
        Server objServer = new Server(12345);

        if (objServer.isPortAvailable()) {
            Thread server = new Thread(objServer);
            server.start();
            //
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ya se encuentra una sala creada", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdesk = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(904, 600));
        setMinimumSize(new java.awt.Dimension(904, 600));
        setPreferredSize(new java.awt.Dimension(904, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(904, 600));

        jdesk.setMaximumSize(new java.awt.Dimension(904, 600));
        jdesk.setMinimumSize(new java.awt.Dimension(904, 600));
        jdesk.setPreferredSize(new java.awt.Dimension(904, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jdesk;
    // End of variables declaration//GEN-END:variables
}
