package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class InternalFrmUnirsePartida extends javax.swing.JInternalFrame {

    FrmMainPanel objMainPanel;
    String rango;
    String color;

    public InternalFrmUnirsePartida(FrmMainPanel objMainPanel, String rango) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        this.objMainPanel = objMainPanel;
        this.rango = rango;

        color = "";

        if (rango.equals("Admin")) {
            jPanelMain.remove(lblSalir);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblSalir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRojo = new javax.swing.JLabel();
        lblMorado = new javax.swing.JLabel();
        lblElegido = new javax.swing.JLabel();
        lblAmarillo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblVerde = new javax.swing.JLabel();
        panelBorder1 = new recursos.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(904, 600));
        setMinimumSize(new java.awt.Dimension(904, 600));
        setPreferredSize(new java.awt.Dimension(904, 600));

        jPanelMain.setLayout(null);

        txtNombre.setBackground(new java.awt.Color(252, 252, 252));
        txtNombre.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelMain.add(txtNombre);
        txtNombre.setBounds(100, 140, 310, 50);

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/regresar.png"))); // NOI18N
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanelMain.add(lblSalir);
        lblSalir.setBounds(30, 40, 32, 40);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanelMain.add(jLabel2);
        jLabel2.setBounds(100, 90, 340, 50);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecciona un Color:");
        jPanelMain.add(jLabel3);
        jLabel3.setBounds(100, 240, 260, 50);

        lblRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/colorFicha3.png"))); // NOI18N
        lblRojo.setPreferredSize(new java.awt.Dimension(74, 74));
        lblRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRojoMousePressed(evt);
            }
        });
        jPanelMain.add(lblRojo);
        lblRojo.setBounds(330, 310, 74, 74);

        lblMorado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/colorFicha1.png"))); // NOI18N
        lblMorado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMoradoMousePressed(evt);
            }
        });
        jPanelMain.add(lblMorado);
        lblMorado.setBounds(100, 310, 74, 74);

        lblElegido.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lblElegido.setPreferredSize(new java.awt.Dimension(74, 74));
        jPanelMain.add(lblElegido);
        lblElegido.setBounds(740, 310, 74, 74);

        lblAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/colorFicha2.png"))); // NOI18N
        lblAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAmarilloMousePressed(evt);
            }
        });
        jPanelMain.add(lblAmarillo);
        lblAmarillo.setBounds(220, 310, 73, 74);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("- - - - - - -");
        jPanelMain.add(jLabel4);
        jLabel4.setBounds(570, 320, 160, 60);

        lblVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/colorFicha4.png"))); // NOI18N
        lblVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVerdeMousePressed(evt);
            }
        });
        jPanelMain.add(lblVerde);
        lblVerde.setBounds(440, 310, 74, 74);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBorder1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingresar");
        panelBorder1.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanelMain.add(panelBorder1);
        panelBorder1.setBounds(320, 440, 230, 60);

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ip:");
        jPanelMain.add(jLabel6);
        jLabel6.setBounds(500, 90, 87, 50);

        lblIp.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lblIp.setText("localhost");
        jPanelMain.add(lblIp);
        lblIp.setBounds(500, 140, 320, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/fondo2.jpg"))); // NOI18N
        jPanelMain.add(jLabel1);
        jLabel1.setBounds(0, 0, 904, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        objMainPanel.agregarInternalFrmMenu();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblMoradoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMoradoMousePressed
        ImageIcon icono = new ImageIcon("src/src/colorFicha1.png");
        lblElegido.setIcon(icono);
        color = "Morado";
    }//GEN-LAST:event_lblMoradoMousePressed

    private void lblAmarilloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmarilloMousePressed
        ImageIcon icono = new ImageIcon("src/src/colorFicha2.png");
        lblElegido.setIcon(icono);
        color = "Amarillo";
    }//GEN-LAST:event_lblAmarilloMousePressed

    private void lblRojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRojoMousePressed
        ImageIcon icono = new ImageIcon("src/src/colorFicha3.png");
        lblElegido.setIcon(icono);
        color = "Rojo";
    }//GEN-LAST:event_lblRojoMousePressed

    private void lblVerdeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerdeMousePressed
        ImageIcon icono = new ImageIcon("src/src/colorFicha4.png");
        lblElegido.setIcon(icono);
        color = "Verde";
    }//GEN-LAST:event_lblVerdeMousePressed

    private void panelBorder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorder1MouseClicked
        if (!txtNombre.getText().isEmpty() && !color.isEmpty()) {
            objMainPanel.crearJugador(rango.toUpperCase(), txtNombre.getText().toUpperCase(), color.toUpperCase());
            if (lblIp.getText().isEmpty()) {
                lblIp.setText("localhost");
            }
            
            if (objMainPanel.ingresarServer(lblIp.getText())) {
                objMainPanel.agregarInternalFrmTablero();
            }else{
                JOptionPane.showMessageDialog(this, "No fue posible establecer conexion", "Error", JOptionPane.ERROR_MESSAGE);
            }
            

        }


    }//GEN-LAST:event_panelBorder1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JLabel lblAmarillo;
    private javax.swing.JLabel lblElegido;
    private javax.swing.JTextField lblIp;
    private javax.swing.JLabel lblMorado;
    private javax.swing.JLabel lblRojo;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblVerde;
    private recursos.PanelBorder panelBorder1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
