package vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class InternalFrmTablero extends javax.swing.JInternalFrame implements Runnable {

    FrmMainPanel objMainPanel;

    String[] config;
    List<String[]> jugadores = new ArrayList<>(); 

    public InternalFrmTablero(FrmMainPanel objMainPanel) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        this.objMainPanel = objMainPanel;

        txtArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String[] datosPartida = txtArea.getText().split("\n");
                String ultimalineaStr = datosPartida[datosPartida.length - 1];
                String[] ultimalinea = ultimalineaStr.split(",");
                if (ultimalinea[0].equals("CP")) {
                    config = ultimalinea;
                } else if (ultimalinea[0].equals("CJ")) {
                    jugadores.add(ultimalinea);
                    String nombre = ultimalinea[2];
                    int turno = Integer.parseInt(ultimalinea[ultimalinea.length-1]);
                    switch (turno) {
                        case 1:
                            lbl1.setText(nombre);
                            break;
                        case 2:
                            lbl2.setText(nombre);
                            break;
                        case 3:
                            lbl3.setText(nombre);
                            break;
                        case 4:
                            lbl4.setText(nombre);
                            break;
                        default:
                            System.out.println("DefaultSwitchTablero");
                    }
                }else if(ultimalineaStr.equals("SALA-LLENA")){
                    JOptionPane.showMessageDialog(null, "La sala se encuentra llena");
                    objMainPanel.agregarInternalFrmMenu();
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                // Método llamado cuando se elimina texto
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Este método se llama cuando se cambian atributos del documento (por ejemplo, estilos)
            }
        });
    }

    public void agregarJugadores() {
        for (int i = 0; i < Integer.parseInt(config[0]); i++) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jscroll = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(904, 600));
        setMinimumSize(new java.awt.Dimension(904, 600));
        setPreferredSize(new java.awt.Dimension(904, 600));

        jPanel1.setLayout(null);

        lbl1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Esperando Admin...");
        jPanel1.add(lbl1);
        lbl1.setBounds(30, 30, 250, 80);

        lbl4.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("Esperando Jugador...");
        jPanel1.add(lbl4);
        lbl4.setBounds(600, 400, 270, 70);

        lbl2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Esperando Jugador...");
        jPanel1.add(lbl2);
        lbl2.setBounds(610, 30, 270, 70);

        lbl3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Esperando Jugador...");
        jPanel1.add(lbl3);
        lbl3.setBounds(30, 400, 270, 70);

        jscroll.setEnabled(false);
        jscroll.setMaximumSize(new java.awt.Dimension(64, 20));
        jscroll.setMinimumSize(new java.awt.Dimension(64, 20));

        txtArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtArea.setEnabled(false);
        jscroll.setViewportView(txtArea);

        jPanel1.add(jscroll);
        jscroll.setBounds(600, 320, 250, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 904, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jscroll;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    public static javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

    }
}
